[package]
name = "mockall_mock_a_sensor"
version = "0.1.0"
authors = ["Michael Abel <mabel@bitmuster.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = ">=0.13.1"
rand = ">=0.9.2"
